### ISSUE TITLE
Query for series

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/yaml-yugipedia#3]
Needed to obtain all the localisations for the names of the series from the wikitext template `Infobox archseries`

**Comment by kevinlul** [comment]
Should be able to use https://yugipedia.com/wiki/Category:TCG_and_OCG_archetypes
However, we only need to store the `Infobox archseries` template at the start of the document and watch that part for updates. Content changes to the remainder of the text do not matter.

**Comment by kevinlul** [comment]
The main end objective here is to obtain localizations for the series names, since the `archseries` field of cards uses the page names, i.e. the English name. Finding hierarchical relationships between series is not strictly necessary, as cards will be correctly annotated with all of them. Hierarchical relationships would require digging into other types of MediaWiki queries, or Semantic MediaWiki.

**Comment by AlphaKretin** [comment]
After some investigation, it was determined that SMW cannot return the information we want about archseries. We're currently scraping the OCG and TCG Archetypes category, but this does not cover all archseries. However, the Series category is not restricted to OCG and TCG cards. So either we filter out archseries without translations to display only archetypes, or scrape Series and filter out any that don't appear in an archseries field.

**Comment by kevinlul** [comment]
d19402fe37b7eb901da1e24b96f96d152da25bd5
3a10e32497ff1dfd7654093411add0ee49712866
03126d245010d64c8b955558189906701b149045

**Comment by kevinlul** [comment]
Considering this complete for now.
